package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"goAPI/graphql/graph/model"
)

// UpdateEndpoint is the resolver for the updateEndpoint field.
func (r *mutationResolver) UpdateEndpoint(ctx context.Context, input *model.UpdateEndpointinput) (*model.Endpoint, error) {
	panic(fmt.Errorf("not implemented: UpdateEndpoint - updateEndpoint"))
}

// Endpoints is the resolver for the endpoints field.
func (r *queryResolver) Endpoints(ctx context.Context) ([]*model.Endpoint, error) {
	panic(fmt.Errorf("not implemented: Endpoints - endpoints"))
}

// Endpoint is the resolver for the endpoint field.
func (r *queryResolver) Endpoint(ctx context.Context, id string) (*model.Endpoint, error) {
	panic(fmt.Errorf("not implemented: Endpoint - endpoint"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
