[api]
port_1 = ":3001"
port_2 = ":3002"
port_graphql = ":8080"

[database]
host = ""
password = ""
user = ""
port = "3306"
name = ""

[redis]
addr = "localhost:6379"
password = ""
db = 0

[jwt]
secret = ""
